project:
  type: website
  title: "SMLP2022"
  execute-dir: project
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - useful_packages.qmd
    - pkg.qmd
    - sleepstudy.qmd
    - sleepstudy_speed.qmd
    - arrow.qmd
    - glmm.qmd
    - kb07.qmd
    - kwdyz11.qmd
    - kkl15.qmd
    - shrinkageplot.qmd
    - contrasts_fggk21.qmd
    - contrasts_kwdyz11.qmd

website:
  title: "SMLP2022"
  site-url: https://RePsychLing.github.io/SMLP2022
  repo-url: https://github.com/RePsychLing/SMLP2022
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/RePsychLing/SMLP2022
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - useful_packages.qmd
      - pkg.qmd
      - sleepstudy.qmd
      - sleepstudy_speed.qmd
      - arrow.qmd
      - glmm.qmd
      - kb07.qmd
      - kwdyz11.qmd
      - kkl15.qmd
      - shrinkageplot.qmd
      - contrasts_fggk21.qmd
      - contrasts_kwdyz11.qmd
  page-navigation: true

date: today
date-format: iso

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
