project:
  type: website
  title: "SMLP2022"
  execute-dir: project
  output-dir: _site
  render:
    - notebooks/useful_packages.ipynb
    - notebooks/mmt_sleepstudy.ipynb
    - notebooks/mmt_sleepstudy_speed.ipynb
    - notebooks/Arrow.ipynb
    - notebooks/glmm.ipynb
    - notebooks/mmt_kb07.ipynb

website:
  title: "SMLP2022 - Advanced frequentist methods"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute: 
  keep-ipynb: true

date: today
date-format: iso

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    css: styles.css

jupyter: julia-1.7
