project:
  type: website
  title: "SMLP2022"
  execute-dir: project
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - notebooks/useful_packages.qmd
    - notebooks/mmt_sleepstudy.qmd
    - notebooks/mmt_sleepstudy_speed.qmd
    - notebooks/Arrow.qmd
    - notebooks/glmm.qmd
    - notebooks/mmt_kb07.qmd

website:
  title: "SMLP2022"
  site-url: https://RePsychLing.github.io/SMLP2022
  repo-url: https://github.com/RePsychLing/SMLP2022
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Packages"
        href: notebooks/useful_packages.qmd
      - text: "Sleepstudy"
        href: notebooks/mmt_sleepstudy.qmd
    right:
      - icon: github
        href: https://github.com/RePsychLing/SMLP2022

execute: 
  keep-ipynb: true

date: today
date-format: iso

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    css: styles.css

jupyter: julia-1.8
