project:
  type: website
  title: "SMLP2022"
  execute-dir: project
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - useful_packages.qmd
    - pkg.qmd
    - sleepstudy.qmd
    - sleepstudy_speed.qmd
    - largescaledesigned.qmd
    - arrow.qmd
    - glmm.qmd
    - kb07.qmd
    - kwdyz11.qmd
    - kkl15.qmd
    - shrinkageplot.qmd
    - contrasts_fggk21.qmd
    - contrasts_kwdyz11.qmd
    # - participants/bahmanian/Bahmanian_NumberAgreement_Julia.qmd
    # - participants/bahmanian/Bahmanian_NumberAgreement_R.qmd
    # - participants/bakay/Bakay_SMPL_Julia.qmd
    # - participants/bakay/Bakay_SMPL_R.qmd
    # - participants/cajar/2_Cajar_IAT_R.qmd
    # - participants/cajar/3_Cajar_IAT_Julia.qmd
    # - participants/cajar/4_Cajar_IAT_groups_R.qmd
    # - participants/cajar/5_Cajar_IAT_arrowconvert.qmd
    # - participants/cajar/6_Cajar_IAT_modelfitting.qmd
    # - participants/hofmann1/Hofmann_Maulwurf_Julia_1.qmd
    # - participants/hofmann1/Hofmann_Maulwurf_Julia_2.qmd
    # - participants/hofmann1/Hofmann_Maulwurf_R.qmd
    # - participants/kliegl/Huber_NobelNovice_R.qmd
    # - participants/kliegl/Kliegl_contrasts_fggk21.qmd
    # - participants/kliegl/Kliegl_contrasts_kwdyz11.qmd
    # - participants/kliegl/Kliegl_LMMbasics_fggk21.qmd
    # - participants/laubrock/Laubrock_EM_Julia_1.qmd
    # - participants/laubrock/Laubrock_EM_Julia_2.qmd
    # - participants/lindemann/Lindemann_NumMeaning_Julia.qmd
    # - participants/lindemann/Lindemann_NumMeaning_R.qmd
    # - participants/maquate/Maquate_LanguageEvaluation_Julia.qmd
    # - participants/maquate/Maquate_LanguageEvaluation_R.qmd
    # - participants/raveling/Raveling_ConversationGaps_Julia_v2.qmd
    # - participants/raveling/Raveling_ConversationGaps_R_v2.qmd
    # - participants/schoengrundner/Schoengrundner_Julia.qmd
    # - participants/schoengrundner/Schoengrundner_R.qmd
    # - participants/vanoncini/Vanoncini_CRQA_Julia.qmd
    # - participants/vanoncini/Vanoncini_CRQA_R.qmd

website:
  title: "SMLP2022"
  site-url: https://RePsychLing.github.io/SMLP2022
  repo-url: https://github.com/RePsychLing/SMLP2022
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/RePsychLing/SMLP2022
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - useful_packages.qmd
      - pkg.qmd
      - sleepstudy.qmd
      - sleepstudy_speed.qmd
      - largescaledesigned.qmd
      - arrow.qmd
      - glmm.qmd
      - kb07.qmd
      - kwdyz11.qmd
      - kkl15.qmd
      - shrinkageplot.qmd
      - contrasts_fggk21.qmd
      - contrasts_kwdyz11.qmd
  page-navigation: true

date: today
date-format: iso
execute:
  freeze: auto  # re-render only when source changes
  cache: true
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
